# Generated by Django 3.2.5 on 2023-05-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_software'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
