# Generated by Django 3.2.5 on 2023-06-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('vip', models.BooleanField(default=True)),
            ],
        ),
    ]
