# Generated by Django 3.2.5 on 2023-06-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='verification',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
