# Generated by Django 3.2.5 on 2023-07-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_qrcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
