# Generated by Django 3.2.5 on 2023-07-02 10:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_fileclass_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/')),
                ('view_count', models.IntegerField(blank=True, default=0)),
                ('time', models.DateTimeField(auto_now=True, null=True)),
                ('vip', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('0', '发布中'), ('1', '未发布')], max_length=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fileclass',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
