# Generated by Django 3.2.5 on 2023-07-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20230702_1016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='FileClass',
        ),
    ]
