# Generated by Django 3.2.5 on 2023-07-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20230702_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='file',
        ),
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/'),
        ),
    ]
