# Generated by Django 3.2.5 on 2022-08-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_classification_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='index_show',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
