# Generated by Django 3.2.5 on 2023-06-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_index_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vip',
            field=models.BooleanField(default=True),
        ),
    ]
