# Generated by Django 3.2.5 on 2023-06-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='vip',
            field=models.BooleanField(default=True),
        ),
    ]
